on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4

        - name: Run my Action
          id: run-action
          uses: ashutoshjadhav9/action-try@v1.1 # Commit with the `v1` tag
          with:
                milliseconds: 1000

        - name: Print Output
          id: output
          run: echo "${{ steps.run-action.outputs.time }}"
