on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3
  
    - name: Test Local Action
      id: test-action
      uses: ./
      with:
        milliseconds: 1000000
  
    - name: Print Output
      id: output
      run: echo "${{ steps.test-action.outputs.time }}"
